version: "3"
 
services:
  # rabbitmq3:
  #       container_name: "rabbitmq_ak_authentication_service"
  #       image: rabbitmq:3.8-management-alpine
  #       env_file:
  #         - .env
  #       ports:
  #           # AMQP protocol port
  #           - '5673:5672'
  #           # HTTP management UI
  #           - '15673:15672'
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  app:
    container_name: "asset_management"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/src
    ports:
      - 8000:8000
    env_file:
      - .env